services:
  postgresdb:
    image: postgres:16.3
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=postgres
#    volumes:
#      - db-data:/Users/taimur.ali/pg-data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  todo-app:
    container_name: todo_app_${DEPLOY_ENVIRONMENT}
    depends_on:
    - postgresdb
    build:
      context: .
      dockerfile: Dockerfile
    image: todo-app
    ports:
      - 8000:8000
    environment:
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgresdb
      - DB_PORT=5432
    command:
      -
volumes:
  db-data:
    driver: local
      - DB_PORT= 5432
